<nav class="navbar navbar-expand-lg menu">
	<div class="container">
	  <div class="navbar-nav">
	  	<a class="menuItem" href="/timeline">
	  		Home
	  	</a>

	  	<a class="menuItem" href="/sair">
	  		Sair
	  	</a>
			<img src="/img/twitter_logo.png" class="menuIco" />
	  </div>
	</div>
</nav>

<div class="container mt-5">
	<div class="row pt-2">
		
		<div class="col-md-3">

			<div class="perfil">
				<div class="perfilTopo">

				</div>

				<div class="perfilPainel">
					
					<div class="row mt-2 mb-2">
						<div class="col mb-2">
							<span class="perfilPainelNome">Nome do Usuário</span>
						</div>
					</div>

					<div class="row mb-2">

						<div class="col">
							<span class="perfilPainelItem">Tweets</span><br />
							<span class="perfilPainelItemValor">0</span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguindo</span><br />
							<span class="perfilPainelItemValor">0</span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguidores</span><br />
							<span class="perfilPainelItemValor">0</span>
						</div>

					</div>

				</div>
			</div>

		</div>

		<div class="col-md-6">
			
			<div class="row mb-2">
				<div class="col">
					<div class="card">
						<div class="card-body">
							<!--action que dispara o metodo quem seguir do app controler, passando a informação pelo metodo get.
								atribuir names aos inputs-->
							<form method="get" action="/quem_seguir">
								<div class="input-group mb-3">
									<input type="text" name="pesquisarPor" class="form-control" placeholder="Quem você está procurando?">
									<div class="input-group-append">
										<button class="btn btn-primary" type="submit">Procurar</button>
									</div>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>

			<!--adicionar um foreach, para cada interação, recebe os dados de cada um dos usuarios encontrados(valor) e adiciona na view-->
			<?php foreach($this->view->usuarios as $indice_arr => $usuario) { ?>
			<div class="row mb-2">
				<div class="col">
					<div class="card">
						<div class="card-body">
							<div class="row">
								<div class="col-md-6">
									<!--Usuário, atraves da variavel do array, recuperar o indice nome--><?= $usuario['nome']?>
								</div>
							
								<div class="col-md-6 d-flex justify-content-end">
									<div>
										<!--passar o parametro seguindo_sn que foi definido na query do metodo getall do usuariophp, para saber se ja segue ou nao, para mostrar o botao de seguir ou deixar de seguir -->
										<!--passar a rota /acao passando 2 parametros na url(get), =seguir e =deixar_de_seguir e o indice ID da variavel $usuario-->

										<?php if($usuario['seguindo_sn'] == 0){ ?>
										<a href="/acao?acao=seguir&id_usuario=<?=$usuario['id']?>" class="btn btn-success">Seguir</a> <?php } ?>

										<?php if($usuario['seguindo_sn'] == 1){ ?>
										<a href="/acao?acao=deixar_de_seguir&id_usuario=<?=$usuario['id']?>" class="btn btn-danger">Deixar de seguir</a> <?php } ?>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div> <?php } ?>

		</div>
	</div>
</div>