<nav class="navbar navbar-expand-lg menu">
	<div class="container">
	  <div class="navbar-nav">
	  	<a class="menuItem" href="/timeline">
	  		Home
	  	</a>

	  	<a class="menuItem" href="/sair">
	  		Sair
	  	</a>
			<img src="/img/twitter_logo.png" class="menuIco" />
	  </div>
	</div>
</nav>

<div class="container mt-5">
	<div class="row pt-2">
		
		<div class="col-md-3">

			<div class="perfil">
				<div class="perfilTopo">

				</div>

				<div class="perfilPainel">

					<!--fazer a impressao das informações dinamicas declaradas no appcontroler e no model usuario. os nomes dos indices, sao os (as) que denifinimos nas contagens das querys-->
					
					<div class="row mt-2 mb-2">
						<div class="col mb-2">
							<span class="perfilPainelNome"><?= $this->view->info_usuario['nome'] ?></span>
						</div>
					</div>

					<div class="row mb-2">

						<div class="col">
							<span class="perfilPainelItem">Tweets</span><br />
							<span class="perfilPainelItemValor"><?= $this->view->total_tweets['total_tweet'] ?></span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguindo</span><br />
							<span class="perfilPainelItemValor"><?= $this->view->total_seguindo['total_seguindo'] ?></span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguidores</span><br />
							<span class="perfilPainelItemValor"><?= $this->view->total_seguidores['total_seguidores'] ?></span>
						</div>

					</div>

				</div>
			</div>

		</div>

		<div class="col-md-6">
			<div class="row mb-2">
				<div class="col tweetBox">

					<!--adicionar nesse form a action com a rota /tweet e o metodo post para ao disparar, fazer a instancia em appcontroller e dispara action tweet, que é quem testa se o usuario esta autenticado, caso esteja, exibe os dados do formulario recebidos pela POST

					defenir name no textarea, pra que seja possivel receber a informação na POST-->
					<form method="post" action="/tweet">
						<textarea class="form-control" name="tweet" id="exampleFormControlTextarea1" rows="3"></textarea>
						
						<div class="col mt-2 d-flex justify-content-end">
							<button type="submit" class="btn btn-primary">Tweet</button>
						</div>

					</form>
				</div>
			</div>

			<!--criar um foreach(estrutura de repetição, que vai percorrer this->view->tweets do appcontrole, e para cada tweet que conter no atributo,vamos recuperar o id do tweet e os seus dados -->
			<?php foreach($this->view->tweets as $id_tweet => $tweet){ ?>
			<div class="row tweet">
				<div class="col">
					<p><strong><!--Nome do Usuário, acessa o array tweet, que foi return FethAll no model--><?=$tweet['nome']?></strong> <span class="text text-muted"> <!--data tweet, return fethall no model-->-<?=$tweet['data']?></span></p>
					<p><!--conteudo tweet, return fethall no model--><?=$tweet['tweet']?></p>

					<br />
					<!--adicionar botao de remover tweet apenas se o dono do tweet(idusuario), for o mesmo dono da sessao aberta.(sessionid)-->
					<!--o botao ainda nao esta funcionando, vou fazer a logica depois, que no caso é bem parecida com a logica do deixar_de_seguir-->
					<?php if($tweet['id_usuario'] == $_SESSION['id']){ ?> 
					<form>
						<div class="col d-flex justify-content-end">
							<button type="submit" class="btn btn-danger"><small>Remover</small></button>
						</div> <?php } ?>
					</form>		
				</div>
			</div><?php } ?>

			<!--PAGINAÇÃO(tem no bootstrap o modelo estatico)-->
			<div class="row">
				<nav aria-label="...">
			  <ul class="pagination">
			    <li class="page-item">
			      <a class="page-link" href="?pagina=1" tabindex="-1">Primeira</a>
			    </li>
			    
			    <!--criar uma variavel i=1, sera menor ou igual ao total de paginas, e cada interação, recebe +1.
			    no href atribui dinamicamente a variavel do for na url(via get) para poder usar na logica-->
			    <?php for($i = 1; $i <= $this->view->total_de_paginas; $i++){ ?>
			    <!--caso a pagina ativa for igual a $i, adicionamos o class active, senao nao fazemos nada-->
			    <li class="page-item <?=$this->view->pagina_ativa == $i ? 'active' : '' ?>">
			    	<a class="page-link" href="?pagina=<?=$i?>"><?=$i?></a>
			    </li>
				<?php } ?>
			    
			    <li class="page-item">
			      <a class="page-link" href="?pagina=<?=$this->view->total_de_paginas?>">Ultima</a>
			    </li>
			  </ul>
			</nav>
			</div>


		</div>


		<div class="col-md-3">
			<div class="quemSeguir">
				<span class="quemSeguirTitulo">Quem seguir</span><br />
				<hr />
				<a href="/quem_seguir" class="quemSeguirTxt">Procurar por pessoas conhecidas</a>
			</div>
		</div>

	</div>
</div>